from __future__ import annotations

from artifact_skill.core.artifact import ArtifactRef, ArtifactType
from tests.conftest import FIXTURES_DIR


def test_pdf_detected_by_content_not_extension():
    ref = ArtifactRef.from_path(FIXTURES_DIR / "good_2page.pdf")
    assert ref.type == ArtifactType.PDF


def test_html_content_with_pdf_extension_is_detected_as_html(mislabeled_html_pdf):
    """The whole point of spec #7: never trust '.pdf' alone."""
    ref = ArtifactRef.from_path(mislabeled_html_pdf)
    assert ref.type == ArtifactType.HTML


def test_corrupt_pdf_is_still_type_pdf_by_header(corrupt_pdf):
    """A %PDF- header is enough to type it PDF even if the body is broken;
    *readability* is a separate, later concern (adapter.inspect / verify)."""
    ref = ArtifactRef.from_path(corrupt_pdf)
    assert ref.type == ArtifactType.PDF


def test_missing_file_raises_input_error(tmp_path):
    import pytest

    from artifact_skill.core.errors import ArtifactInputError

    with pytest.raises(ArtifactInputError):
        ArtifactRef.from_path(tmp_path / "does_not_exist.pdf")


def test_hash_is_stable_for_same_content(good_pdf):
    ref1 = ArtifactRef.from_path(good_pdf)
    ref2 = ArtifactRef.from_path(good_pdf)
    assert ref1.sha256 == ref2.sha256
    assert len(ref1.sha256) == 64


# --- leading comment before the doctype/root tag (Issue #26) --------------
#
# A license banner or generator comment before <!DOCTYPE html>/<?xml?>/<svg>
# is an extremely common real-world pattern - the original bare
# startswith() prefix check couldn't see past it at all, sniffing an
# unambiguously-HTML/SVG file as UNKNOWN.


def test_html_with_a_leading_comment_before_doctype_is_still_detected(tmp_path):
    path = tmp_path / "licensed.html"
    path.write_text("<!-- Copyright 2026 Example Corp. All rights reserved. -->\n<!doctype html>\n<html></html>")
    assert ArtifactRef.from_path(path).type == ArtifactType.HTML


def test_html_with_a_leading_comment_before_bare_html_tag_is_still_detected(tmp_path):
    """No <!DOCTYPE> at all - just <html> after the comment."""
    path = tmp_path / "no_doctype.html"
    path.write_text("<!-- generated by tool vX.Y -->\n<html><body>hi</body></html>")
    assert ArtifactRef.from_path(path).type == ArtifactType.HTML


def test_html_with_multiple_leading_comments_is_still_detected(tmp_path):
    path = tmp_path / "double_comment.html"
    path.write_text("<!-- first --><!-- second -->\n<!doctype html><html></html>")
    assert ArtifactRef.from_path(path).type == ArtifactType.HTML


def test_svg_with_a_leading_comment_before_xml_prolog_is_still_detected(tmp_path):
    path = tmp_path / "licensed.svg"
    path.write_text(
        '<!-- Licensed under CC-BY 4.0 -->\n<?xml version="1.0" encoding="UTF-8"?>\n'
        '<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10"></svg>'
    )
    assert ArtifactRef.from_path(path).type == ArtifactType.SVG


def test_svg_with_a_leading_comment_before_bare_svg_tag_is_still_detected(tmp_path):
    """No XML prolog at all - just <svg> after the comment, a common
    hand-authored/tool-exported shape."""
    path = tmp_path / "no_prolog.svg"
    path.write_text('<!-- exported from Design Tool --><svg xmlns="http://www.w3.org/2000/svg"></svg>')
    assert ArtifactRef.from_path(path).type == ArtifactType.SVG


def test_an_unterminated_leading_comment_is_left_as_unknown_not_misdetected(tmp_path):
    """The closing --> never appears at all: detect_type() must not guess
    past it - UNKNOWN is the honest answer here, not a silent misdetection."""
    path = tmp_path / "broken.html"
    path.write_text("<!-- this comment never closes <!doctype html><html></html>")
    assert ArtifactRef.from_path(path).type == ArtifactType.UNKNOWN


# --- CFB/OLE2 container detection (Issue #27) ------------------------------
#
# A password-protected Office 2007+ file (.pptx/.docx/.xlsx saved with
# encryption) isn't a zip at all - Office wraps the whole encrypted package
# in a Compound File Binary (CFB, aka "OLE2") container, the same container
# format legacy pre-2007 binary Office files (.doc/.ppt/.xls) use for their
# own, unrelated reasons. The 8-byte signature tested here
# (D0 CF 11 E0 A1 B1 1A E1) is fixed by the MS-CFB spec - every real file in
# either category starts with exactly these bytes, not something specific
# to any one file this project could have generated itself.

_CFB_MAGIC = b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1"


def test_cfb_ole2_container_is_detected_as_its_own_type_not_unknown(tmp_path):
    path = tmp_path / "password_protected.pptx"
    path.write_bytes(_CFB_MAGIC + b"\x00" * 512)  # real CFB files carry more header after the signature
    assert ArtifactRef.from_path(path).type == ArtifactType.OLE_COMPOUND_FILE


def test_cfb_detection_applies_regardless_of_file_extension(tmp_path):
    """Spec #7 applies here too - a CFB file mislabeled .zip must still be
    detected by content, not by its (wrong) extension."""
    path = tmp_path / "mislabeled.zip"
    path.write_bytes(_CFB_MAGIC + b"\x00" * 512)
    assert ArtifactRef.from_path(path).type == ArtifactType.OLE_COMPOUND_FILE
